image: docker:latest

services:
    - docker:20.10.24-dind

variables:
    DOCKER_DRIVER: overlay2
    SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
    - build

package:
    stage: build
    variables:
        IMAGE_TAG: "$CI_REGISTRY_IMAGE:latest"
    rules:
        -   if: ($CI_COMMIT_REF_NAME == "main")
    script:
        - docker build -t $IMAGE_TAG .
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
        - docker push $IMAGE_TAG
