version: '3.9'
services:
  # Integra Convert Service
  integra:
    image: integra-unoserver:latest
    deploy:
      resources:
        limits:
          memory: 1024M

  nginx:
    image: nginx:alpine
    ports:
      - "4201:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - integra
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
